### ISSUE TITLE
Minor Grammatical (Farewell, Farwell)

### ISSUE THREAD

**Issue by VivaRado** [KIT-MRT/iv2022_workshop_bridging_the_gap#1]
https://github.com/KIT-MRT/iv2022_workshop_bridging_the_gap/edit/gh-pages/index.md :29 
Should be **Conclusion and Farewell** not Farwell

**Comment by FranklynJey** [comment]
Thanks! I will correct it

**Comment by FranklynJey** [comment]
it is corrected
